---
title: "Livros Gratuitos da Springer"
author: "Steven Dutt Ross"
date: "03/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# LIVROS

Acabei de saber por um amigo sobre o [Marcus Nunes' Blog](https://marcusnunes.me/posts/livros-gratuitos-da-springer/) que a editora Springer disponibilizou mais de 500 livros gratuitamente. 

Boa oportunidade de fazer um backup e treinar raspagem de dados.

Basta visitar o site e baixar, sem sequer necessitar fazer cadastro. 
A lista completa de livros está no site do Marcus Nunes emplanilha do Excel, mas abaixo eu coloquei a listagem de livros de Matemática e Estatística. O site dele é muito bom. aqui está o link. [https://marcusnunes.me/posts/](https://marcusnunes.me/posts/)


 [1] "[A Beginner’s Guide to R](http://link.springer.com/openurl?genre=book&isbn=978-0-387-93837-0)"                                       
 [2] "[A Modern Introduction to Probability and Statistics](http://link.springer.com/openurl?genre=book&isbn=978-1-84628-168-6)"           
 [3] "[A Primer on Scientific Programming with Python](http://link.springer.com/openurl?genre=book&isbn=978-3-662-49887-3)"                
 [4] "[A Pythagorean Introduction to Number Theory](http://link.springer.com/openurl?genre=book&isbn=978-3-030-02604-2)"                   
 [5] "[Abstract Algebra](http://link.springer.com/openurl?genre=book&isbn=978-3-319-77649-1)"                                              
 [6] "[Algebra](http://link.springer.com/openurl?genre=book&isbn=978-1-4613-0041-0)"                                                       
 [7] "[All of Statistics](http://link.springer.com/openurl?genre=book&isbn=978-0-387-21736-9)"                                             
 [8] "[An Introduction to Statistical Learning](http://link.springer.com/openurl?genre=book&isbn=978-1-4614-7138-7)"                       
 [9] "[Applied Linear Algebra](http://link.springer.com/openurl?genre=book&isbn=978-3-319-91041-3)"                                        
[10] "[Applied Multivariate Statistical Analysis](http://link.springer.com/openurl?genre=book&isbn=978-3-662-45171-7)"                     
[11] "[Applied Partial Differential Equations](http://link.springer.com/openurl?genre=book&isbn=978-3-319-12493-3)"                        
[12] "[Applied Predictive Modeling](http://link.springer.com/openurl?genre=book&isbn=978-1-4614-6849-3)"                                   
[13] "[Applied Quantitative Finance](http://link.springer.com/openurl?genre=book&isbn=978-3-662-54486-0)"                                  
[14] "[Bayesian and Frequentist Regression Methods](http://link.springer.com/openurl?genre=book&isbn=978-1-4419-0925-1)"                   
[15] "[Bayesian Essentials with R](http://link.springer.com/openurl?genre=book&isbn=978-1-4614-8687-9)"                                    
[16] "[Brownian Motion, Martingales, and Stochastic Calculus ](http://link.springer.com/openurl?genre=book&isbn=978-3-319-31089-3)"        
[17] "[Business Statistics for Competitive Advantage with Excel 2016 ](http://link.springer.com/openurl?genre=book&isbn=978-3-319-32185-1)"
[18] "[Calculus With Applications](http://link.springer.com/openurl?genre=book&isbn=978-1-4614-7946-8)"                                    
[19] "[Classical Fourier Analysis](http://link.springer.com/openurl?genre=book&isbn=978-1-4939-1194-3)"                                    
[20] "[Complex Analysis](http://link.springer.com/openurl?genre=book&isbn=978-1-4419-7288-0)"                                              
[21] "[Design and Analysis of Experiments](http://link.springer.com/openurl?genre=book&isbn=978-3-319-52250-0)"                            
[22] "[Differential Equations and Their Applications](http://link.springer.com/openurl?genre=book&isbn=978-1-4612-4360-1)"                 
[23] "[Discrete Mathematics](http://link.springer.com/openurl?genre=book&isbn=978-0-387-21777-2)"                                          
[24] "[Elementary Analysis](http://link.springer.com/openurl?genre=book&isbn=978-1-4614-6271-2)"                                           
[25] "[Fundamentals of Clinical Trials](http://link.springer.com/openurl?genre=book&isbn=978-3-319-18539-2)"                               
[26] "[Introduction to Partial Differential Equations](http://link.springer.com/openurl?genre=book&isbn=978-3-319-48936-0)"                
[27] "[Introduction to Partial Differential Equations](http://link.springer.com/openurl?genre=book&isbn=978-3-319-02099-0)"                
[28] "[Introduction to Smooth Manifolds](http://link.springer.com/openurl?genre=book&isbn=978-1-4419-9982-5)"                              
[29] "[Introduction to Statistics and Data Analysis ](http://link.springer.com/openurl?genre=book&isbn=978-3-319-46162-5)"                 
[30] "[Introduction to Time Series and Forecasting](http://link.springer.com/openurl?genre=book&isbn=978-3-319-29854-2)"                   
[31] "[Introductory Statistics with R](http://link.springer.com/openurl?genre=book&isbn=978-0-387-79054-1)"                                
[32] "[Introductory Time Series with R](http://link.springer.com/openurl?genre=book&isbn=978-0-387-88698-5)"                               
[33] "[Linear Algebra](http://link.springer.com/openurl?genre=book&isbn=978-3-319-24346-7)"                                                
[34] "[Linear Algebra Done Right](http://link.springer.com/openurl?genre=book&isbn=978-3-319-11080-6)"                                     
[35] "[Methods of Mathematical Modelling](http://link.springer.com/openurl?genre=book&isbn=978-3-319-23042-9)"                             
[36] "[Modeling Life](http://link.springer.com/openurl?genre=book&isbn=978-3-319-59731-7)"                                                 
[37] "[Multivariate Calculus and Geometry](http://link.springer.com/openurl?genre=book&isbn=978-1-4471-6419-7)"                            
[38] "[Numerical Optimization](http://link.springer.com/openurl?genre=book&isbn=978-0-387-40065-5)"                                        
[39] "[Ordinary Differential Equations](http://link.springer.com/openurl?genre=book&isbn=978-1-4614-3618-8)"                               
[40] "[Partial Differential Equations](http://link.springer.com/openurl?genre=book&isbn=978-1-4614-4809-9)"                                
[41] "[Probability](http://link.springer.com/openurl?genre=book&isbn=978-1-4612-4374-8)"                                                   
[42] "[Probability Theory](http://link.springer.com/openurl?genre=book&isbn=978-1-4471-5201-9)"                                            
[43] "[Probability Theory](http://link.springer.com/openurl?genre=book&isbn=978-1-4471-5361-0)"                                            
[44] "[Proofs from THE BOOK](http://link.springer.com/openurl?genre=book&isbn=978-3-662-57265-8)"                                          
[45] "[Quantum Theory for Mathematicians](http://link.springer.com/openurl?genre=book&isbn=978-1-4614-7116-5)"                             
[46] "[Reading, Writing, and Proving](http://link.springer.com/openurl?genre=book&isbn=978-1-4419-9479-0)"                                 
[47] "[Real Analysis](http://link.springer.com/openurl?genre=book&isbn=978-1-4939-2766-1)"                                                 
[48] "[Regression Modeling Strategies](http://link.springer.com/openurl?genre=book&isbn=978-3-319-19425-7)"                                
[49] "[Representation Theory](http://link.springer.com/openurl?genre=book&isbn=978-1-4612-0979-9)"                                         
[50] "[Statistical Analysis and Data Display](http://link.springer.com/openurl?genre=book&isbn=978-1-4939-2122-5)"                         
[51] "[Statistical Learning from a Regression Perspective](http://link.springer.com/openurl?genre=book&isbn=978-3-319-44048-4)"            
[52] "[Statistics and Data Analysis for Financial Engineering](http://link.springer.com/openurl?genre=book&isbn=978-1-4939-2614-5)"        
[53] "[Survival Analysis](http://link.springer.com/openurl?genre=book&isbn=978-1-4419-6646-9)"                                             
[54] "[The Elements of Statistical Learning](http://link.springer.com/openurl?genre=book&isbn=978-0-387-84858-7)"                          
[55] "[Time Series Analysis](http://link.springer.com/openurl?genre=book&isbn=978-0-387-75959-3)"                                          
[56] "[Understanding Analysis](http://link.springer.com/openurl?genre=book&isbn=978-1-4939-2712-8)"                                        
[57] "[Understanding Statistics Using R](http://link.springer.com/openurl?genre=book&isbn=978-1-4614-6227-9)"                      