---
lead_author_surname: Dutt-Ross
footer: "https://steven.metodosquantitativos.com/"
keywords:
  - Wordclouds
  - Tweets
  - webscraper
footer_contents: "DATAUNIRIO & ECOPOL"
output:
  pdf_document: 
    includes:
      in_header: definicoes.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#\pagecolor{yellow!30!orange}
```

\fullboxbegin

## MINICURSO - INTRODUCAO À ANÁLISE DE REDES SOCIAIS      
## COM A LINGUAGEM DE PROGRAMAÇÃO R    

\fullboxend

## Carga Horária: 10 Horas
## Coordenador: João Roberto Lopes
## Professor: Steven Dutt-Ross  
## Semestre: 2º Ano: 2022
  
\fullboxbegin
## Plano de Ensino
\fullboxend


### Descrição, objetivo e conteúdo

Compreender as interconexões entre entidades como pessoas e organizações tornou-se parte importante da pesquisa em ciências sociais. Assim, neste minicurso, discutiremos como analisar de forma prática as relações sociais e como raciocinar sobre elas por meio de modelos de estrutura de rede. Nesse sentido, discutiremos os modelos de grafos. Os tópicos adicionais a serem abordados incluirão influência e detecção da estrutura de grupos e comunidade. Os(as) alunos(as) farão experiências em dados de rede do mundo real e serão capazes de construir uma rede a partir de dados brutos e avaliar as características de estrutura de rede subjacente para extrair insights úteis.


\rightboxbegin

Para instalar o R, visite o site:      
https://www.r-project.org/      
Para instalar o RStudio, visite o site:      
https://www.rstudio.com/     

\rightboxend



### Objetivos

O objetivo central do curso é promover a capacidade de criar códigos para análise de redes sociais utilizando a linguagem de programação R.

### Programação

\textbf{1. Termos e Conceitos - Dia 11/10/2022}   

1. Tipo de dados  
2. Distância em redes  
3. Revisão de matriz (matriz quadrada)     
4. Matriz de ligações     
5. Graficos de rede     
6. Medidas de centralidade    
  6.1 closeness    
  6.2 betweenness    
  6.3 degree    
  6.4 eigenvector    
7. Grupos e comunidades     
8. Hub e Autoridade    
9. Estudos de Casos      
  
   
\textbf{2. Aplicação no R - Dia 18/10/2022}
   
1. Introdução/revisão de R
2. Dados (data.frame, matrizes) no R
3. Carregar dados no R
4. Converter dados em rede com o R
5. Construir gráficos de redes com o R
6. Usar cores em gráficos de rede
7. Usar tamanho em gráficos de Rede
  
  
\textbf{3. Aplicação no R (parte 2) - Dia 25/10/2022}    
   
1. Distância geodésica com o R     
2. Cálculo de Medidas de Centralidade   
3. Identificação de grupos/comunidades com o R    
4. O estado da arte     
  4.1 desafios e principais problemas que encontrei   
  4.2 aprendendo a usar a melhor ferramenta de redes (gephi network analysis)   
  
  
\fullboxbegin 
  
### Bibliografia básica  
  
HANNEMAN,R.; RIDDLE,M. *Introduction to social network methods*,  2005.  Disponível em http://faculty.ucr.edu/~hanneman/nettext/Introduction_to_Social_Network_Methods.pdf  
  
\fullboxend
  
   
  
## Bibliografia complementar    

AQUINO, J. A. de *R para cientistas sociais* – Ilhéus, BA: EDITUS, 2014. 157 p.

BARBERA, P. *Introduction to social network analysis with R*, 2017. Disponível em http://pablobarbera.com/big-data-upf/html/02a-networks-intro-visualization.html

KOLACZYK, E. D.; CSÁRDI, G. *Statistical analysis of network data with R*. New York, NY: Springer, 2014.

SHIZUKA, DAI . *Intro to Network Analysis in R* Disponível em https://dshizuka.github.io/networkanalysis/

WICKHAM, H. and GROLEMUND, G.*R for data science: import, tidy, transform, visualize, and model data.*" O'Reilly Media, Inc.", 2016.   

## Referência - pacotes do R

ALLAIRE,J; GANDRUD, C; RUSSELL, K; YETMAN, C _networkD3: D3 JavaScript Network Graphs from R_. 2017.

CSARDI, G. and NEPUSZ, T.  *The igraph software package for complex network research*, 2006. InterJournal, Complex Systems. https://igraph.org/r/

R CORE TEAM *R: A language and environment for statistical computing.* R Foundation for Statistical Computing, Vienna, Austria. 2022. https://www.R-project.org/.

 

\leftboxbegin
Para saber mais, visite o site:  

https://dataunirio.github.io/  

\leftboxend


